### ISSUE TITLE
Invalid level_idc: 8

### ISSUE THREAD

**Issue by irannapattar** [sourcey/libsourcey#263]
Hi, 

I am trying to run webrtcrecorder native application, but getting an error. 

here is the error:

```
[libx264 @ 0x7fd0e8001600] invalid level_idc: 8
06:41:29 [error] [multiplexencoder.cpp(153)] Error: Cannot open the video codec: Generic error in an external library
06:41:29 [error] [streamrecorder.cpp(88)] Failed to init encoder: std::exception
```
here are the logs of webrtcrecorder:

```06:41:22 [debug] [signaler.cpp(116)] Client state changed from Closed to Connecting
06:41:22 [debug] [application.cpp(104)] Wait for shutdown
06:41:22 [debug] [signaler.cpp(116)] Client state changed from Connecting to Connected
06:41:22 [debug] [client.cpp(364)] On handshake: sid=P2giOM6u3Enj48sMAAAA, pingInterval=25000, pingTimeout=60000
06:41:22 [debug] [client.cpp(387)] Peer connected:videorecorder|P2giOM6u3Enj48sMAAAA
06:41:22 [debug] [signaler.cpp(116)] Client state changed from Connected to Online
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [signaler.cpp(71)] Peer connected: fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [client.cpp(387)] Peer connected:demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peer.cpp(130)] fy01Ym63r5cvHalGAAAB: Receive offer: v=0
o=- 5759510838313019636 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MBJH
a=ice-pwd:Yobxr4622eSCwSAGCb96htcQ
a=ice-options:trickle
a=fingerprint:sha-256 ED:D2:34:BA:86:A8:5C:AA:BE:98:73:11:19:30:87:FB:98:ED:E6:2F:35:B7:F8:8D:CC:33:4F:C3:B2:F2:27:82
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2656400221 cname:YPBcZKcz5rTp+Z49
a=ssrc:2656400221 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH 521ecb52-d3e6-4319-9051-24a77bb2d15e
a=ssrc:2656400221 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:2656400221 label:521ecb52-d3e6-4319-9051-24a77bb2d15e
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MBJH
a=ice-pwd:Yobxr4622eSCwSAGCb96htcQ
a=ice-options:trickle
a=fingerprint:sha-256 ED:D2:34:BA:86:A8:5C:AA:BE:98:73:11:19:30:87:FB:98:ED:E6:2F:35:B7:F8:8D:CC:33:4F:C3:B2:F2:27:82
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 x-google-profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=123
a=rtpmap:114 ulpfec/90000
a=ssrc-group:FID 1851356384 4069795887
a=ssrc:1851356384 cname:YPBcZKcz5rTp+Z49
a=ssrc:1851356384 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:1851356384 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:1851356384 label:d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:4069795887 cname:YPBcZKcz5rTp+Z49
a=ssrc:4069795887 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:4069795887 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:4069795887 label:d3baba81-0198-46f7-8a87-4e910d4e287a

06:41:28 [debug] [peer.cpp(165)] fy01Ym63r5cvHalGAAAB: On signaling state change: 3
06:41:28 [debug] [peer.cpp(225)] fy01Ym63r5cvHalGAAAB: On add stream
06:41:28 [debug] [peermanager.cpp(64)] Received offer: v=0
o=- 5759510838313019636 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MBJH
a=ice-pwd:Yobxr4622eSCwSAGCb96htcQ
a=ice-options:trickle
a=fingerprint:sha-256 ED:D2:34:BA:86:A8:5C:AA:BE:98:73:11:19:30:87:FB:98:ED:E6:2F:35:B7:F8:8D:CC:33:4F:C3:B2:F2:27:82
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2656400221 cname:YPBcZKcz5rTp+Z49
a=ssrc:2656400221 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH 521ecb52-d3e6-4319-9051-24a77bb2d15e
a=ssrc:2656400221 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:2656400221 label:521ecb52-d3e6-4319-9051-24a77bb2d15e
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MBJH
a=ice-pwd:Yobxr4622eSCwSAGCb96htcQ
a=ice-options:trickle
a=fingerprint:sha-256 ED:D2:34:BA:86:A8:5C:AA:BE:98:73:11:19:30:87:FB:98:ED:E6:2F:35:B7:F8:8D:CC:33:4F:C3:B2:F2:27:82
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 x-google-profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 H264/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:123 red/90000
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=123
a=rtpmap:114 ulpfec/90000
a=ssrc-group:FID 1851356384 4069795887
a=ssrc:1851356384 cname:YPBcZKcz5rTp+Z49
a=ssrc:1851356384 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:1851356384 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:1851356384 label:d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:4069795887 cname:YPBcZKcz5rTp+Z49
a=ssrc:4069795887 msid:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH d3baba81-0198-46f7-8a87-4e910d4e287a
a=ssrc:4069795887 mslabel:hOpKhxBG7mH99jAPjDGhqFMvsuLadf8WuoPH
a=ssrc:4069795887 label:d3baba81-0198-46f7-8a87-4e910d4e287a

06:41:28 [debug] [peer.cpp(329)] On SDP parse success
06:41:28 [debug] [peer.cpp(255)] fy01Ym63r5cvHalGAAAB: Set local description
06:41:28 [debug] [peer.cpp(165)] fy01Ym63r5cvHalGAAAB: On signaling state change: 0
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:2999745851 1 udp 2122260223 192.168.56.1 59849 typ host generation 0 ufrag MBJH network-id 2
06:41:28 [debug] [peer.cpp(185)] fy01Ym63r5cvHalGAAAB: On ICE connection change: 1
06:41:28 [debug] [peer.cpp(329)] On SDP parse success
06:41:28 [debug] [peer.cpp(191)] fy01Ym63r5cvHalGAAAB: On ICE gathering change: 1
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:564218470 1 udp 2122194687 100.64.100.204 59850 typ host generation 0 ufrag MBJH network-id 1 network-cost 10
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:2999745851 1 udp 2122260223 192.168.56.1 59851 typ host generation 0 ufrag MBJH network-id 2
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:564218470 1 udp 2122194687 100.64.100.204 59852 typ host generation 0 ufrag MBJH network-id 1 network-cost 10
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:4233069003 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 ufrag MBJH network-id 2
06:41:28 [debug] [signaler.cpp(89)] Peer message: demo|fy01Ym63r5cvHalGAAAB
06:41:28 [debug] [peermanager.cpp(85)] Received candidate: candidate:1864545942 1 tcp 1518214911 100.64.100.204 9 typ host tcptype active generation 0 ufrag MBJH network-id 1 network-cost 10
06:41:28 [debug] [peer.cpp(191)] fy01Ym63r5cvHalGAAAB: On ICE gathering change: 2
06:41:29 [debug] [peer.cpp(185)] fy01Ym63r5cvHalGAAAB: On ICE connection change: 2
[libx264 @ 0x7fd0e8001600] invalid level_idc: 8
06:41:29 [error] [multiplexencoder.cpp(153)] Error: Cannot open the video codec: Generic error in an external library
06:41:29 [error] [streamrecorder.cpp(88)] Failed to init encoder: std::exception
```

I have reduced the webcam resolution using external wecam(manycam), then also no success. 
what could be the issue?

**Comment by irannapattar** [comment]
But after that I am getting Segmentation Fault (core dumped)

Here is the log:
```
[libx264 @ 0x7fbdec001600] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 LZCNT BMI1
[libx264 @ 0x7fbdec001600] profile High, level 3.2
Segmentation fault (core dumped)
```
Even I have tried to track with gdb and backtrace but couldnt help.
```
[libx264 @ 0x7fffa4001600] profile High, level 3.2

Thread 19 "IncomingVideoSt" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd76fd700 (LWP 6776)]
0x00000001000001e0 in ?? ()
(gdb) bt
#0  0x00000001000001e0 in ?? ()
#1  0x00007ffff5380c6c in x264_stack_align () from /usr/lib/x86_64-linux-gnu/libx264.so.155
#2  0x00007fffd76f710c in ?? ()
#3  0x00007fffd76f7110 in ?? ()
#4  0x0000000000000000 in ?? ()
```

**Comment by auscaster** [comment]
This has been resolved in the icey v2 rewrite. The library has been completely modernised with C++20, new build system, updated dependencies (OpenSSL 3.x, FFmpeg 5+, libuv 1.50), and rewritten modules. If you're still experiencing a related issue on the latest version, please open a new issue.
